steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/my-flood-project-480015/flood-api', '-f', 'api/Dockerfile', '.']
images:
  - 'gcr.io/my-flood-project-480015/flood-api'
